# Generated by Django 5.2.1 on 2025-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
