# Generated by Django 5.2.1 on 2025-05-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_active',
            new_name='is_expire',
        ),
    ]
